# Generated by Django 5.2 on 2025-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('age', models.IntegerField()),
                ('name', models.TextField(max_length=100)),
                ('hobby', models.TextField(max_length=100)),
                ('profession', models.TextField(max_length=100)),
            ],
        ),
    ]
